##===- tools/COTPasses/Makefile ----------------------------*- Makefile -*-===##

LEVEL = ../..

LIBRARYNAME = COTPasses

LOADABLE_MODULE = 1

USEDLIBS = cotInstructionCount.a cotHelloLLVM.a cotFunctionEraser.a \
	   cotDataDependencyGraph.a cotControlDependencyGraph.a \
	   cotProgramDependencyGraph.a

include $(LEVEL)/Makefile.common
